---
title: "`r commandArgs(trailingOnly=T)[1]`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(stargazer)
library(knitr)
library(DT)

load('../output/results_simplified.RData')

mname= commandArgs(trailingOnly=T)[2]
vifs_model = eval(parse(text=paste0('rbindlist(lapply(', mname, ', function(x) x$vif))')))
# elasticities
elast_model = eval(parse(text=paste0('rbindlist(lapply(', mname, ', function(x) x$elast))')))
results_model = eval(parse(text=paste0(mname)))

```


## Example model specification for one brand

Let us first look at the model results for *one* example brand. I've generated this to illustrate the model configuration (i.e., covariates) and dependent variable.

```{r, results = 'asis', echo = FALSE}
ids = unlist(lapply(results_model, function(x) x$elast$brand_id[1]))
bid=1372
id=which(ids==bid)

stargazer(results_model[[id]]$model, type='html')
cat(paste0('Dependent variable: ', colnames(results_model[[id]]$model$model)[id]), fill =T)

```

## Summary of elasticities

### by variable type

```{r, echo = FALSE}

tmp = elast_model[!is.na(elastlt), list(N=.N,mean=mean(elastlt), min=min(elastlt), max = max(elastlt), sd=sd(elastlt)),by=c('variable')]
kable(tmp)
```

### by variable type

```{r, echo = FALSE}

tmp = elast_model[!is.na(elastlt), list(N=.N,mean=mean(elastlt), q01 = quantile(elastlt,.01),
                                   q01 = quantile(elastlt,.01),
                                   q025 = quantile(elastlt,.025),
                                   q05 = quantile(elastlt,.05),
                                   q10 = quantile(elastlt,.10),
                                   q50 = quantile(elastlt,.5),
                                   q80 = quantile(elastlt,.8),
                                   q90 = quantile(elastlt,.90),
                                   q95 = quantile(elastlt,.95),
                                   q975 = quantile(elastlt,.975),
                                   q99 = quantile(elastlt,.99)),by=c('variable')]

kable(tmp)
```

### by category and variable type

```{r, echo = FALSE}

tmp = elast_model[!is.na(elastlt), list(N=.N,mean=mean(elastlt), min=min(elastlt), max = max(elastlt), sd=sd(elastlt)),by=c('variable', 'category')]
setorder(tmp,variable, category)

kable(tmp)

```

## Summary of VIFs

### by covariate

```{r, echo = FALSE}

tmp = vifs_model[, list(N=.N,mean=mean(vif), min=min(vif), max = max(vif)),by=c('variable')]
setorderv(tmp,'mean', order=-1L)

kable(tmp, caption = 'VIFs, ordered in descending order of mean VIFs')

```

### by category

```{r, echo = FALSE}

tmp = vifs_model[, list(N=.N,mean=mean(vif), min=min(vif), max = max(vif)),by=c('category')]
setorderv(tmp,'mean', order=-1L)

kable(tmp, caption = 'VIFs, ordered in descending order of mean VIFs')

```

### for a few example models

```{r, echo  = FALSE, results = 'asis'}
for (bid in c(10,100,1000)) print(kable(vifs_model[brand_id==bid], caption = paste0('VIFs for brand_id ', bid)))
```



```{r, echo = FALSE, include = FALSE}
### VIFs (scrollable table in descending order of VIFs, capped at 1000 entries)
if(0){
tmp=vifs_model
setorderv(tmp, 'vif',order=-1L)
DT::datatable(head(tmp,1000))
### VIFs (scrollable table without product attributes in descending order of VIFs, capped at 1000 entries)

tmp=vifs_model[!grepl('attr[_]', variable)]
setorderv(tmp, 'vif',order=-1L)
DT::datatable(head(tmp,1000))
}
```
