---
title: "GfK Singapore"
output:
  html_document: default
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(data.table)
require(stargazer)
library(knitr)
require(xtable)
require(texreg)
library(sjstats)

options(xtable.comment = FALSE)

# Load results
  load(file = c('../temp/results_20171113.RData'))

# determine model to analyze
  results_brands <- results_MNL
  
# identify model crashes
	checks <- unlist(lapply(results_brands, class))
	table(checks)
	last.item = length(analysis_markets)

# load data
	brand_panel=fread('../temp/preclean.csv')
	brand_panel[, ':=' (date = as.Date(date))]
	
	# elasticities
	elast <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$elast))

	# merge some more variables to it
	vars = c('cat_class', 'country_class')
	tmp = brand_panel[, c('market_id', vars), with=F]
	setkey(tmp, market_id)
	tmp = unique(tmp)
	
	elast = merge(elast, tmp, all.x=T, all.y=F, by = c('market_id'))
	
	
new <- c('tablets', 'phones_smart')

wb_lowermidx = c('india','indonesia', 'vietnam', 'philippines')
wb_uppermidx = c('china', 'malaysia','thailand')


elast[, new:=category%in%new]
elast[, wb_lowermid:=country%in%wb_lowermidx]
elast[, wb_uppermid:=country%in%wb_uppermidx]

elast[, low := wb_lowermid+wb_uppermid]

tableno<<-0
figureno<<-0
fig<-function(caption) {figureno<<-figureno+1;paste0('Figure ', figureno, ': ', caption)}
tab<-function(caption) {tableno<<-tableno+1;paste0('Table ', tableno, ': ', caption)}
```

# Estimation sample
## Overview
```{r overview, echo=FALSE}
cat('Number of markets: ', length(unique(elast$market_id)), '\n')
cat('Number of brands (sum of unique brands per market): ', nrow(elast[, .N, by = c('market_id', 'brand')]),'\n')
cat('Number of unique brands: ', nrow(elast[, .N, by = c('brand')]))
```

```{r brand_activity, echo=FALSE,results='asis'}
tmp=elast[, list(ncountries=length(unique(country))), by = c('brand')]

hist(tmp$ncountries,main=fig('Distribution of active brands by number of countries (estimation data)'), xlab='countries',breaks=20,xlim=c(1,15),cex.main=.8)
tmp=data.table(table(tmp$ncountries))
setnames(tmp, c('number of countries', 'active brands'))
print(xtable(tmp,caption=tab('Frequency table of active brands by number of countries (estimation data)')),include.rownames=FALSE,type='html',longtable=T,caption.placement='top')

```

```{r overview2, echo=FALSE, results='asis'}

tmp = elast[, list(Nbrands = length(unique(brand))), by = c('market_id', 'category','country')]

tabl = dcast(tmp, category~country, value.var=c('Nbrands'))
print(xtable(tabl, caption = tab('Overview of included categories and countries (with number of brands indicated for each market), in estimation data')), scalebox='0.6',type='html',caption.placement='top')


```

```{r elast_overall, echo = FALSE, results='asis'}

	zval=1.64
	tmp=elast[!is.na(coef), list(median_elast = median(elast), 
												  w_elast = sum(elast/elast_se)/sum(1/elast_se), 
												  N_brands= .N, 
												  perc_positive = length(which(z>=(zval)))/.N, 
												  perc_null = length(which(abs(z)<zval))/.N, 
												  perc_negative = length(which(z<=(-zval)))/.N), by=c('variable')]
	print(xtable(tmp, caption = tab('Elasticities by variable for all brands (significance tested at p<.1 (z >= 1.64).')),type='html',caption.placement='top')
	

	if(0){# Copulas
	copulas <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$model@coefficients))
	copulas <- copulas[grepl('cop_', varname)]
	
	tmp=copulas[!is.na(coef), list(median = median(coef), 
											  weighted = sum(coef/se)/sum(1/se), 
											  N_brands= .N, 
											  perc_positive = length(which(z>=(zval)))/.N, 
											  perc_null = length(which(abs(z)<zval))/.N, 
											  perc_negative = length(which(z<=(-zval)))/.N), by=c('varname')]

	kable(tmp, caption = 'Copula terms by variable (used for getting an understanding about significance)')
}

```
## ANOVAs
```{r anova_full, echo=FALSE,results='asis', warning=FALSE}

for (i in unique(elast$variable)) {
  m<-aov(elast~brand+country+category, data=elast, subset=variable==i)
  print(xtable(anova_stats(m), caption = tab(paste0("ANOVA for marketing mix ", i, ' in FULL sample'))),type='html',caption.placement='top')
}

```

# Selected sample
## Overview
```{r brandselect, echo=FALSE,results='asis'}

elast_select = elast[, ncountries:=length(unique(country)), by = c('brand')]
elast_select = elast_select[ncountries>2]
# exclude
elast_select = elast_select[!brand%in% c('unbranded')]

tmp=elast_select[, list(ncountries=length(unique(country)), ncategories=length(unique(category))), by = c('brand')]
setorderv(tmp, c('ncountries','ncategories'),order=-1L)
print(xtable(tmp, caption=tab('Overview of selected brands (need to be active in at least three countries)')), type='html',caption.placement='top')

```

```{r overview3, echo=FALSE, results='asis'}

tmp = elast_select[, list(Nbrands = length(unique(brand))), by = c('market_id', 'category','country')]

tabl = dcast(tmp, category~country, value.var=c('Nbrands'))
print(xtable(tabl, caption = tab('Overview of included categories and countries (with number of brands indicated for each market), in selected sample')), scalebox='0.6',type='html',caption.placement='top')


```

```{r elast_selected, echo = FALSE, width = 600,results='asis'}

	zval=1.64
	tmp=elast_select[!is.na(coef), list(median_elast = median(elast), 
												  w_elast = sum(elast/elast_se)/sum(1/elast_se), 
												  N_brands= .N, 
												  perc_positive = length(which(z>=(zval)))/.N, 
												  perc_null = length(which(abs(z)<zval))/.N, 
												  perc_negative = length(which(z<=(-zval)))/.N), by=c('variable')]
	print(xtable(tmp, caption = tab('Elasticities by variable in selected sample (significance tested at p<.1 (z >= 1.64).')),type='html',caption.placement='top')
	
	
  if(0){
	# copulas
	copulas <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$model@coefficients))
	copulas <- copulas[grepl('cop_', varname)]
	
	tmp=copulas[!is.na(coef), list(median = median(coef), 
											  weighted = sum(coef/se)/sum(1/se), 
											  N_brands= .N, 
											  perc_positive = length(which(z>=(zval)))/.N, 
											  perc_null = length(which(abs(z)<zval))/.N, 
											  perc_negative = length(which(z<=(-zval)))/.N), by=c('varname')]

	kable(tmp, caption = 'Copula terms by variable (used for getting an understanding about significance)')

  }
```

## ANOVAs
```{r anova, echo=FALSE,results='asis', warning=FALSE}

for (i in unique(elast_select$variable)) {
  m<-aov(elast~brand+country+category, data=elast_select, subset=variable==i)
  print(xtable(anova_stats(m), caption = tab(paste0("ANOVA for marketing mix ", i, ' in SELECTED sample'))),type='html',caption.placement='top')
}

```

## Plots
```{r plots_elast, echo=FALSE, fig.pos="H", include = TRUE,fig.width=12, fig.height=6,dpi=600}

# median elasticities by country

for (i in unique(elast_select$variable)) {
  par(mfrow=c(1,3))
  # by country
  cat(paste0('Variable: ', i, '\n'))
  	tmp=elast_select[!is.na(coef)&variable==i, list(w_elast = sum(elast/elast_se)/sum(1/elast_se)), by=c('variable','country')]
	setorderv(tmp, 'w_elast', ifelse(i=='rwpspr', 1,-1))
	barplot(tmp$w_elast,names.arg=tmp$country, las=2, cex.names=.8, main = fig(paste0(i, ', by countries')),cex.main=.8)
	
	  # by category
  
  	tmp=elast_select[!is.na(coef)&variable==i, list(w_elast = sum(elast/elast_se)/sum(1/elast_se)), by=c('variable','category')]
	setorderv(tmp, 'w_elast', ifelse(i=='rwpspr', 1,-1))
	barplot(tmp$w_elast,names.arg=tmp$category, las=2, cex.names=.8, main = fig(paste0(i, ', by categories')),cex.main=.8)
	
	  # by brand
  
  	tmp=elast_select[!is.na(coef)&variable==i, list(w_elast = sum(elast/elast_se)/sum(1/elast_se)), by=c('variable','brand')]
	setorderv(tmp, 'w_elast', ifelse(i=='rwpspr', 1,-1))
	barplot(tmp$w_elast,names.arg=tmp$brand, las=2, cex.names=.8, main = fig(paste0(i, ', by brands')),cex.main=.8)
	
	  }



```
