---
title: "GfK Singapore"
output:
  html_document
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(data.table)
require(stargazer)
library(knitr)
require(xtable)
require(texreg)
library(sjstats)
library(purtest)

options(xtable.comment = FALSE)

# Load results
load(file = c('../output/results14june2018.RData'))

# determine model to analyze
  results_brands <-  results_nov12sh 
  
# identify model crashes
	checks <- unlist(lapply(results_brands, class))
	table(checks)
	last.item = length(analysis_markets)

# obtain elasticities
	elast <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$elast))

# obtain data on the use of copula terms 
	cops <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) data.table(x$model@coefficients)[!grepl('lagunitsales_sh|dum|trend', varname)&!grepl('quarter', brand), c('varname', 'market_id', 'brand', 'coef','z'),with=F]))

	# split brands
	cops[, copula:='main']
	cops[grepl('cop[_]',varname), copula:='copula']
	
	cops[copula=='copula', varname:=sapply(varname, function(x) strsplit(x, '[_]')[[1]][2])]
	cops[, all:='total']
	
# add indicator to copula
	setkey(cops, market_id, brand, varname)
	setkey(elast, market_id, brand, variable)
	
	elast[cops[copula=='copula'], ':=' (cop_coef = i.coef, cop_z = i.z)]
	
	
	## Load panel data
	brand_panel=fread('../temp/preclean.csv')
	brand_panel[, ':=' (date = as.Date(date))]


# get an idea which brands
tableno<<-0
figureno<<-0
fig<-function(caption) {figureno<<-figureno+1;paste0('Figure ', figureno, ': ', caption)}
tab<-function(caption) {tableno<<-tableno+1;paste0('Table ', tableno, ': ', caption)}
```

# Estimation sample

## Overview

Number of markets: `r length(unique(elast$market_id))`.
Number of brands: `r nrow(elast[, .N, by = c('market_id', 'brand')])`.
Number of unique brands: `r nrow(elast[, .N, by = c('brand')])`.
Number of markets which could not be estimated due to errors: `r length(which(!checks=='list'))`.

```{r elast_overall, echo = FALSE, results='asis'}

.vars=c('llen','wpswdst','rwpspr','nov12sh')
zval=1.64
	
  tmp=elast[!is.na(elast)&!brand%in%c('unbranded','super', 'amazon'), list(w_elast_st = sum(elast/elast_se)/sum(1/elast_se), 
                                w_elast_lt = sum(elastlt/elastlt_se)/sum(1/elastlt_se),
                                N_copula = length(which(!is.na(cop_coef))),
                                N=.N,
                                share_copula=length(which(!is.na(cop_coef)))/.N), by=c('variable')]
  
	kable(tmp[match(.vars, variable)], caption = tab('Short- and long-term elasticities by variable, excluding unbranded, super, and amazon (significance tested at p<.1 (z >= 1.64).'))

	
	#Copulas
	copulas <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$model@coefficients))
	copulas <- copulas[grepl('cop_', varname)]
	

		
	tmp=copulas[!is.na(coef), list(median = median(coef), 
											  N_brands= .N, 
											  perc_positive = length(which(z>=(zval)))/.N, 
											  perc_null = length(which(abs(z)<zval))/.N, 
											  perc_negative = length(which(z<=(-zval)))/.N), by=c('varname')]

	kable(tmp, caption = 'Copula terms by variable (used for getting an understanding about significance)')

			tmp=lapply(c('all', 'varname'), function(bycol) {
	  tmp=cops[, list(total_N=length(which(copula=='main')), total_copula=length(which(copula=='copula'))), by= bycol]
	  tmp[, share:=total_copula/total_N]
	  return(tmp)
	  	})

	kable(tmp[[1]], caption = 'Overall copula share')

	# Normality of potentially endogeneous regressors
	#Copulas
	copulanormality <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$cop_nonnormal))
	
	tmp=copulanormality[!is.na(shap_pval), list(N_tests = .N,
	                                       perc_normal = length(which(shap_pval>.1))/.N,
	                                       perc_nonnormal = length(which(shap_pval<=.1))/.N),
	                                       by=c('variable')]
	
  tmp2=copulanormality[!is.na(shap_pval), list(N_tests = .N,
	                                       perc_normal = length(which(shap_pval>.1))/.N,
	                                       perc_nonnormal = length(which(shap_pval<=.1))/.N)]
	

	kable(tmp, caption = 'Assessing non-normality of marketing mix instruments (by variable)')
	kable(tmp2, caption = 'Assessing non-normality of marketing mix instruments (collapsed)')
	
	# Assessing carry-over coefficients
	tmp <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) x$model@coefficients))
	tmp <- tmp[grepl('lagunitsales[_]', varname)]
	# check markets
	carryover <- data.table(market_id=unlist(lapply(results_brands, function(x) x$market_id)))
	setkey(carryover, market_id)
	setkey(tmp, market_id)
	carryover[tmp, coef:=i.coef]
	carryover[is.na(coef), coef:=0]
	
  benchmark_brands <- rbindlist(lapply(results_brands[!checks=='try-error'], function(x) data.table(market_id=unique(x$specs$market_id), benchmarkbrand = x$benchmark_brand)))
	
```

# Carry-over coefficients
```{r carryover, echo = FALSE, results='asis'}
kable(data.table(t(summary(carryover$coef)))[, ':=' (V1=NULL, value=N, N=NULL)], caption = "Distribution of carry-over coefficients",col.names = NA)
hist(carryover$coef, main = 'Distribution of carry-over coefficients')
```	
	
	
# Panel unit root tests
```{r unitroot, echo = FALSE}

  
  focal_vars <- c('usalessh')

  # extract info on which variables were estimated in the first place

  ur_raw<-data.table(suppressWarnings(melt(brand_panel, id.vars=c('market_id', 'category','country', 'brand', 'date'), measure.vars=focal_vars)))
  ur_raw = ur_raw[!is.na(value)]
  
  # use only data used for estimation
  #setkey(ur_raw, market_id, brand, variable)
  #setkey(elast, market_id, brand, variable)
  #ur_raw[elast, match:=i.variable]
  #ur_raw <- ur_raw[!is.na(match)]
  
  # turn this on if prototyping code
  if(0){
    # variables for prototyping
    .var=focal_vars[1]
    .byvar=c('combined')
  }
  
  # specify tests
  iter = c('market_id', 'individ')#','category', 'country', 'individ')
  
  
  ur_by = rbindlist(lapply(iter, function(.byvar) {
    
    rbindlist(lapply(focal_vars, function(.var) {
      
      if (.byvar=='market_id') ur_data = dcast(ur_raw[variable==.var], market_id+date~brand)
      if (.byvar=='individ') ur_data = ur_raw[variable==.var, list(individ=paste0(market_id,'+',brand), date=date,value = value)]
      
      ur_data[, splitvar := get(.byvar)]
      for (.iter in iter) suppressWarnings(ur_data[, (.iter) := NULL])
      
      te= split(ur_data, ur_data$splitvar)
      
      out=NULL
      for (j in 1:length(te)) {
        test_data=te[[j]]
        print(j)
        splitvar = unique(test_data$splitvar)
        test_data[, ':=' (date=NULL, splitvar=NULL)]
        .inclcols <- colnames(test_data)[!colSums(test_data,na.rm=T)==0]
        test_data=test_data[, .inclcols,with=F]
        test_data[, time:=1:.N]
        tmp=melt(test_data, id.vars=c('time'))
        fwrite(tmp, '../temp/test.csv')
        
        
        if ((ncol(test_data))>0) {
          # Levin-Lin-Chu without demean
          Choi <- pCADFtest(Y=test_data, type = "trend", max.lag.y = 12, criterion = "AIC")

        }
        out[[j]]<-data.table(by = .byvar, name=splitvar, variable=.var, 
                   choi_testval=Choi$statistic, choi_pval=Choi$p.value)
      }
      rbindlist(out)
    }  
      ))
  }))
  
  
#  ur_by <- fread('../output/ur_tests.csv')
test_results=ur_by[, list(N=length(which(!is.na(choi_pval))), N_stationary = length(which(choi_pval<=.1)), N_UR = length(which(choi_pval>.1))), by = c('variable','by')]
print(test_results)

kable(test_results[by=='cat_name'], caption='Summary of UR tests by category')


# try different panel ur

data("OECDunemp")
u=data.frame(OECDunemp[,-8])
u <- log(OECDunemp[,-8]/(100 - OECDunemp[,-8]))
Choi <- pCADFtest(Y=u, type = "drift", max.lag.y = 5, criterion = "AIC")

```
