---
title: "GfK Singapore - Results"
output:
  html_document: default
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

libs_to_load <- c('data.table', 'stargazer', 'knitr', 'xtable', 'car', 'kableExtra', 'stringi', 'ggplot2', 'ggpubr', 'plyr', 'gridExtra', 'grid', 'lme4', 'sjstats') #'blme' 

for (lib in libs_to_load) eval(parse(text=paste('library(', lib, ')')))

options(xtable.comment = FALSE)
options(knitr.kable.NA = '')

# Load data
  elast <- fread('../externals/elast_results_nov12sh.csv') 

  brand_panel=fread('../../analysis/temp/preclean.csv')
  brand_panel[, ':=' (date = as.Date(date))]
  
# Load auxilary functions
  source('proc_auxilary.R')
  source('proc_rename.R')

# Preclean data
  source('preclean.R')
  
# set order of variables to appear in figures and tables
ordered_vars = c('rwpspr', 'wpswdst','llen','nov12sh')
names(ordered_vars) <- paste0(unlist(sanitize_table(data.frame(ordered_vars))), ' elasticity')


  
# formulas for models
form_main_model = .~1+ (1|brand) + (1|category) + (1|country) + emerging + sbbe_std_mc + local_to_market + ln_herf_mc +ln_market_growth_mc +  ln_overall_prindexavg_mc + appliance + gini_mc

form_main_model_selected_interact = .~1+ (1|brand) + (1|category) + (1|country) + emerging + sbbe_std_mc + I(sbbe_std_mc*emerging) + local_to_market + I(local_to_market*emerging) + ln_herf_mc + I(ln_herf_mc*emerging) + ln_market_growth_mc + I(ln_market_growth_mc*emerging) + ln_overall_prindexavg_mc + appliance + gini_mc

#meanglobalx local_multip_market
#local_multip_market +

form_interact = ~1+ (1|brand) + (1|category) + (1|country) + emerging + sbbe_std_mc + I(sbbe_std_mc*emerging) + local_to_market + I(local_to_market*emerging)  +  ln_herf_mc + I(ln_herf_mc*emerging) + ln_market_growth_mc + I(ln_market_growth_mc*emerging) + appliance + I(appliance*emerging) + ln_overall_prindexavg_mc + I(ln_overall_prindexavg_mc*emerging) + gini_mc + I(gini_mc*emerging)

lmerctrl = lmerControl(optimizer ="Nelder_Mead", check.conv.singular="ignore")

#estimtype = 'winsor-onesided'
#estimtype = 'winsor-twosided'
estimtype = 'weighted'
#estimtype = 'nonweighted'

winsor_p=.01

notes_sig = 'Significance levels: \\* *p*<.1, \\*\\* *p*<.05, \\*\\*\\* *p*<.01 (two-sided).'
  
# 1-sided
if (estimtype=='winsor-onesided') {
  
  for (.var in c('elast', 'elastlt')) {
    elast[!is.na(get(.var)), (.var) := winsor_onesided(get(.var), fraction=winsor_p, ifelse(variable=='rwpspr', 'right','left')), by=c('variable')]
    elast[!is.na(get(.var)), paste0('w_', .var) := 1]
    elast[!is.na(get(.var)), paste0('z_', .var) := get(.var)/get(paste0(.var, '_se'))]
  }
   
      estimnote = paste0('Elasticities have been winsorized at ', winsor_p*100, '%, left-sided for all variables except price.')
  estimnoteshort='' 
}

# 2-sided
if (estimtype=='winsor-twosided') {
  
  for (.var in c('elast', 'elastlt')) {
    elast[!is.na(get(.var)), (.var) := winsor_onesided(get(.var), fraction=winsor_p, side='both'), by=c('variable')]
    elast[!is.na(get(.var)), paste0('w_', .var) := 1]
    elast[!is.na(get(.var)), paste0('z_', .var) := get(.var)/get(paste0(.var, '_se'))]
  }
   
      estimnote = paste0('Elasticities have been winsorized at ', winsor_p*100, '%, two-sided.')
  estimnoteshort=''
}

if (estimtype=='weighted') {
  
  for (.var in c('elast', 'elastlt')) {

    elast[!is.na(get(.var)), paste0('w_', .var) := 1/get(paste0(.var, '_se'))]
    # rescale
    elast[!is.na(get(.var)), paste0('w_', .var) := get(paste0('w_', .var))/max(get(paste0('w_', .var)))]
    elast[!is.na(get(.var)), paste0('z_', .var) := get(.var)/get(paste0(.var, '_se'))]
  }
   
      estimnote = paste0('Elasticities are weighted by inverse standard errors.')
      estimnoteshort= 'weighted by inverse standard errors'
  
}


if (estimtype=='nonweighted') {
  
  for (.var in c('elast', 'elastlt')) {

    elast[!is.na(get(.var)), paste0('w_', .var) := 1]
    elast[!is.na(get(.var)), paste0('z_', .var) := get(.var)/get(paste0(.var, '_se'))]
  }
   
      estimnote = paste0('Elasticities are unweighted.')
      estimnoteshort= 'unweighted'
  
}


notes_base = paste0("^1^ Regression of long-term elasticities on explanatory variables and three random effects, for brands, categories, and countries, respectively. Estimated using a linear mixed-effects model. ", estimnote, " Standard errors in parentheses.")

```

```{r continue_with_selection, echo=FALSE}
elast_all=data.table(elast)
elast=elast[!is.na(country_of_origin)&!tolower(brand)%in%c('unbranded')]
excluded_brands=setdiff(unique(elast_all$brand), unique(elast$brand))
excluded_brands<-unique(gsub('Allothers.*', 'Composite brands (allothers)', excluded_brands))

```

Reported for a sample of `r length(unique(elast$brand))` unique brands (excluding `r paste0(my_capitalize(excluded_brands), collapse=', ')`).

```{r plot_2x2, echo=FALSE, include=FALSE}

elast[, interact:=sbbe_std_mc*emerging]

form_main_model = .~1 + emerging + sbbe_std_mc + interact+ (1|country) + (1|category) + (1|brand) + ln_herf_mc + ln_market_growth_mc + appliance + ln_gini_mc + local_to_market

out1=regmodel(formula=c(main=form_main_model), dat=elast, model='lmer')


# keep only models that belong to one type (so that each table only features the rows that were actually estimated)
main = lapply(out1, function(x) x$lt$main)
# example data
index=1


shifter = lapply(main, function(i) {
  vars = grep('_mc|category|country|brand|^elast|(weights)', colnames(i@frame),value=T, invert=T)
  means=sapply(vars, function(x) mean(i@frame[, x]))
  print(means)
  coefs = data.frame(summary(i)$coefficients)
  shifter = coefs['(Intercept)',]$Estimate+coefs['appliance',]$Estimate*means['appliance']+coefs['local_to_market',]$Estimate*means['local_to_market']
  return(shifter)
})

shifter=unlist(shifter)
names(shifter)=names(main)
modvarq=quantile(elast$sbbe_std_mc,c(.25,.75))
emerging = c(0,1)

simdata=data.table(expand.grid(modvar=modvarq, emerging=emerging))

require(car)

sims=rbindlist(lapply(names(main), function(mod) {
  simdata[, form:=paste0(shifter[mod], '+emerging*', emerging,'+sbbe_std_mc*', modvar, ' + interact * ', emerging * modvar)]
  rbindlist(lapply(1:nrow(simdata), function(r) {
    
    tmp=deltaMethod(main[[mod]], simdata[r]$form)
    cbind(model=mod, simdata[r], est=tmp$Estimate, se=tmp$SE)
  }))
}))
```

## 2x2 plots of estimated elasticities

```{r outputbar, echo=F,results='asis'}
#ggplot(sims, aes(x=emerging, y=est, fill=local_to_market)) + geom_bar(stat="identity", position=position_dodge())
sims[, ':=' (l_emerging=ifelse(emerging==1,'EM','DM'),
             l_brandequity=ifelse(modvar==max(modvar), 'strong brand','weak brand'))]
#,
 #            l_local=ifelse(local_to_market==1,'domestic brand','foreign brand'))]

for (mod in unique(sims$model)) {
simtmp=sims[model==mod]
#png(paste0('../audit/plot_', mod, '.png'), res=150, units='in', height=4, width=4)
p<-ggplot(simtmp, aes(x=l_brandequity,y=est, fill = l_emerging)) +geom_bar(stat="identity", position = 'dodge', width= .5) + ggtitle(paste0(rename.fkt(unique(simtmp$model)), ' elasticities')) + xlab('Brand strength') + ylab('Mean elasticity') + labs(fill="Development status") #+  geom_errorbar(position = position_dodge(0.5), aes(ymin=est-1.69*se,ymax=est+1.69*se),width=.25)
print(p)
cat("<P style='page-break-before: always'>")

#dev.off()
}
       
```


# Plots from the data (weighted elasticities)

```{r median, echo=F,results='asis'}
#ggplot(sims, aes(x=emerging, y=est, fill=local_to_market)) + geom_bar(stat="identity", position=position_dodge())
elast[, ':=' (l_emerging=ifelse(emerging==1,'EM','DM'),
             l_brandequity=ifelse(sbbe_std_mc>0, 'strong brand','weak brand'))]


sims = elast[, list(est=sum(elastlt*w_elast)/sum(w_elast)), by = c('variable', 'l_brandequity', 'l_emerging')]


#sims[, ':=' (l_emerging=ifelse(emerging==1,'EM','DM'),
 #            l_brandequity=ifelse(modvar==max(modvar), 'strong brand','weak brand'))]
#,
 #            l_local=ifelse(local_to_market==1,'domestic brand','foreign brand'))]

for (mod in unique(sims$variable)) {
simtmp=sims[variable==mod]
#png(paste0('../audit/plot_', mod, '.png'), res=150, units='in', height=4, width=4)
p<-ggplot(simtmp, aes(x=l_brandequity,y=est, fill = l_emerging)) +geom_bar(stat="identity", position = 'dodge', width= .5) + ggtitle(paste0(rename.fkt(mod), ' elasticities')) + xlab('Brand strength') + ylab('Mean elasticity') + labs(fill="Development status") #+  geom_errorbar(position = position_dodge(0.5), aes(ymin=est-1.69*se,ymax=est+1.69*se),width=.25)
print(p)
cat("<P style='page-break-before: always'>")

#dev.off()
}
       
```



```{r plot_2x2, echo=FALSE, include=FALSE}

elast[, interact:=sbbe_std_mc*emerging]

form_main_model = .~1 + emerging + sbbe_std_mc + interact+ (1|country) + (1|category) + (1|brand) + ln_herf_mc + ln_market_growth_mc + appliance + ln_gini_mc + local_to_market

out1=regmodel(formula=c(main=form_main_model), dat=elast, model='lmer')


# keep only models that belong to one type (so that each table only features the rows that were actually estimated)
main = lapply(out1, function(x) x$lt$main)
# example data
index=1


shifter = lapply(main, function(i) {
  vars = grep('_mc|category|country|brand|^elast|(weights)', colnames(i@frame),value=T, invert=T)
  means=sapply(vars, function(x) mean(i@frame[, x]))
  print(means)
  coefs = data.frame(summary(i)$coefficients)
  shifter = coefs['(Intercept)',]$Estimate+coefs['appliance',]$Estimate*means['appliance']+coefs['local_to_market',]$Estimate*means['local_to_market']
  return(shifter)
})

shifter=unlist(shifter)
names(shifter)=names(main)
modvarq=quantile(elast$sbbe_std_mc,c(.25,.75))
modvarq=seq(from=modvarq[1], to=modvarq[2], by  = .01)

emerging = c(0,1)

simdata=data.table(expand.grid(modvar=modvarq, emerging=emerging))

require(car)

sims=rbindlist(lapply(names(main), function(mod) {
  simdata[, form:=paste0(shifter[mod], '+emerging*', emerging,'+sbbe_std_mc*', modvar, ' + interact * ', emerging * modvar)]
  rbindlist(lapply(1:nrow(simdata), function(r) {
    
    tmp=deltaMethod(main[[mod]], simdata[r]$form)
    cbind(model=mod, simdata[r], est=tmp$Estimate, se=tmp$SE)
  }))
}))
```



## 2x2 plots of estimated elasticities

```{r outputbar, echo=F,results='asis'}
#ggplot(sims, aes(x=emerging, y=est, fill=local_to_market)) + geom_bar(stat="identity", position=position_dodge())
sims[, ':=' (l_emerging=ifelse(emerging==1,'EM','DM'),
             l_brandequity=ifelse(modvar==max(modvar), 'strong brand','weak brand'))]
#,
 #            l_local=ifelse(local_to_market==1,'domestic brand','foreign brand'))]

for (mod in unique(sims$model)) {
simtmp=sims[model==mod]
#png(paste0('../audit/plot_', mod, '.png'), res=150, units='in', height=4, width=4)
p<-ggplot(simtmp, aes(x=l_brandequity,y=est, fill = l_emerging)) +geom_bar(stat="identity", position = 'dodge', width= .5) + ggtitle(paste0(rename.fkt(unique(simtmp$model)), ' elasticities')) + xlab('Brand strength') + ylab('Mean elasticity') + labs(fill="Development status") #+  geom_errorbar(position = position_dodge(0.5), aes(ymin=est-1.69*se,ymax=est+1.69*se),width=.25)
print(p)
cat("<P style='page-break-before: always'>")

#dev.off()
}
       
```


ggplot(data=df, aes(x=dose, y=len, group=1)) +
  geom_line()+
  geom_point()
  